name: Create Daily Issue

on:
  workflow_dispatch:
  schedule:
  # 每天凌晨1点执行
    - cron: '0 1 * * *'

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      # 将代码克隆到工作目录
      - uses: actions/checkout@v2
      # 设置python环境
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      # 安装需要的依赖包
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests pygithub ciqreviews
          
      # 运行py脚本创建issue
      - name: Create daily issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ REPO_NAME }}
        run: |
          python data-scripts/create-issue.py
      
